name: macOs build

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macOs-latest

    steps:
    - uses: actions/checkout@v3

    - name: install dependencies
      run: brew update;
           brew install boost;
           brew install googletest
      
      
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      run: ${{github.workspace}}/build/tests/boost-tcp-server-client-tests 
    
